#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DISTANCE_M="${1:-0.25}"

# Experimental candidate:
# - prioritizes distance completed during flight
# - keeps post-landing catch-up modest
# - uses a slightly more upright push/flight geometry than the earlier
#   balanced airborne probe
# - repeated 0.25 m trials on 2026-03-25 landed around:
#   final=0.245-0.255 m, airborne=0.161-0.165 m, post=0.056-0.063 m
# - touchdown attitude is still heuristic, but materially cleaner than the
#   older 6/4 pitch-target family
export GO2_JUMP_PROFILE="${GO2_JUMP_PROFILE:-aggressive_airborne}"
export GO2_JUMP_USE_TAKEOFF_SPEED_SCALE_CURVE="${GO2_JUMP_USE_TAKEOFF_SPEED_SCALE_CURVE:-false}"
export GO2_JUMP_TAKEOFF_SPEED_SCALE="${GO2_JUMP_TAKEOFF_SPEED_SCALE:-1.04}"
export GO2_JUMP_FLIGHT_LANDING_PREP_MAX_BLEND="${GO2_JUMP_FLIGHT_LANDING_PREP_MAX_BLEND:-0.0}"
export GO2_JUMP_SUPPORT_RELAX_DURATION_S="${GO2_JUMP_SUPPORT_RELAX_DURATION_S:-0.0}"
export GO2_JUMP_SUPPORT_THIGH_RAD="${GO2_JUMP_SUPPORT_THIGH_RAD:-1.06}"
export GO2_JUMP_SUPPORT_CALF_RAD="${GO2_JUMP_SUPPORT_CALF_RAD:--2.04}"
export GO2_JUMP_SUPPORT_FRONT_COMPACT_DELTA_RAD="${GO2_JUMP_SUPPORT_FRONT_COMPACT_DELTA_RAD:--0.04}"
export GO2_JUMP_SUPPORT_REAR_COMPACT_DELTA_RAD="${GO2_JUMP_SUPPORT_REAR_COMPACT_DELTA_RAD:-0.12}"
export GO2_JUMP_PUSH_FRONT_TAU_SCALE="${GO2_JUMP_PUSH_FRONT_TAU_SCALE:-1.04}"
export GO2_JUMP_PUSH_REAR_TAU_SCALE="${GO2_JUMP_PUSH_REAR_TAU_SCALE:-1.04}"
export GO2_JUMP_PUSH_PITCH_TARGET_DEG="${GO2_JUMP_PUSH_PITCH_TARGET_DEG:-8.0}"
export GO2_JUMP_FLIGHT_PITCH_TARGET_DEG="${GO2_JUMP_FLIGHT_PITCH_TARGET_DEG:-6.0}"
export GO2_JUMP_PUSH_FRONT_COMPACT_DELTA_RAD="${GO2_JUMP_PUSH_FRONT_COMPACT_DELTA_RAD:--0.155}"
export GO2_JUMP_PUSH_REAR_COMPACT_DELTA_RAD="${GO2_JUMP_PUSH_REAR_COMPACT_DELTA_RAD:-0.055}"
export GO2_JUMP_FLIGHT_FRONT_COMPACT_DELTA_RAD="${GO2_JUMP_FLIGHT_FRONT_COMPACT_DELTA_RAD:-0.24}"
export GO2_JUMP_FLIGHT_REAR_COMPACT_DELTA_RAD="${GO2_JUMP_FLIGHT_REAR_COMPACT_DELTA_RAD:--0.14}"
export GO2_JUMP_LANDING_SUPPORT_BLEND="${GO2_JUMP_LANDING_SUPPORT_BLEND:-0.30}"
export GO2_JUMP_RECOVERY_UPRIGHT_BLEND="${GO2_JUMP_RECOVERY_UPRIGHT_BLEND:-0.70}"

"${ROOT_DIR}/scripts/docker_run_single_jump_trial.sh" "${TARGET_DISTANCE_M}"
